/*
 * Copyright 2026 Hypergiant Galactic Systems Inc. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

/**
 * THIS IS A GENERATED FILE. DO NOT ALTER DIRECTLY.
 * Generated by smeegl.
 */

export const COFFIN_CORNER_HOVER = 'coffin-corner-hover';
export const COFFIN_CORNER_SELECTED = 'coffin-corner-selected';
export const COFFIN_CORNER_SELECTED_HOVER = 'coffin-corner-selected-hover';
export const MARKER = 'marker';
export const MARKER_SERIOUS = 'marker-serious';
