ls:
  .dir: kebabcase | screamingsnakecase
  .md: kebabcase | screamingsnakecase
  .js: kebabcase
  .jsx: kebabcase
  .mjs: kebabcase
  .cjs: kebabcase
  .ts: kebabcase
  .tsx: kebabcase
  .*.js: kebabcase
  .*.jsx: kebabcase
  .*.mjs: kebabcase
  .*.cjs: kebabcase
  .*.ts: kebabcase
  .*.tsx: kebabcase

ignore:
  - .changeset
  - .git
  - .github
  - .turbo
  - .vscode
  - .agents
  - node_modules
  - '**/.next'
  - '**/.ladle'
  - '**/.storybook'
  - '**/.turbo'
  - '**/__*__'
  - '**/build'
  - '**/coverage'
  - '**/dist'
  - '**/node_modules'
  - '**/.docusaurus'
