ls:
  .dir: kebabcase | screamingsnakecase
  .md: kebabcase | screamingsnakecase
  .js: kebabcase
  .jsx: kebabcase
  .mjs: kebabcase
  .cjs: kebabcase
  .ts: kebabcase
  .tsx: kebabcase
  .*.js: kebabcase
  .*.jsx: kebabcase
  .*.mjs: kebabcase
  .*.cjs: kebabcase
  .*.ts: kebabcase
  .*.tsx: kebabcase

ignore:
  - .git
  - .ladle
  - .turbo
  - .vscode
  - .changeset
  - .github
  - __fixtures__
  - __snapshots__
  - node_modules
  - build
  - '**/*/.turbo'
  - '**/*/.ladle'
  - '**/*/__fixtures__'
  - '**/*/__snapshots__'
  - '**/*/node_modules'
  - '**/*/coverage'
  - '**/*/dist'
  - '**/*/build'
