packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"
  - "design-toolkit/*"
onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@parcel/watcher"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - "core-js"
  - "core-js-pure"
  - "es5-ext"
  - "esbuild"
  - "lefthook"
  - "msw"
  - "sharp"
packageExtensions:
  "react-aria-components@1.8.0":
    peerDependencies:
      "@types/react": "^19.0.10"
