packages:
  - apps/*
  - packages/*
  - tooling/*

enablePrePostScripts: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - lefthook
  - puppeteer
  - sharp
  - sleep

# https://pnpm.io/settings#publichoistpattern
publicHoistPattern:
  - "*@vitest/coverage-istanbul*"
  - "*prettier-plugin-tailwindcss*"
