// @ts-nocheck
import * as __fd_glob_45 from "../content/toolkits/design-toolkit/api/components/text-field/index.md?collection=docs"
import * as __fd_glob_44 from "../content/toolkits/design-toolkit/api/components/table/index.md?collection=docs"
import * as __fd_glob_43 from "../content/toolkits/design-toolkit/api/components/dialog/index.md?collection=docs"
import * as __fd_glob_42 from "../content/toolkits/design-toolkit/api/components/button/index.md?collection=docs"
import * as __fd_glob_41 from "../content/toolkits/design-toolkit/api/components/badge/index.md?collection=docs"
import * as __fd_glob_40 from "../content/packages/bus/api/broadcast/index.md?collection=docs"
import * as __fd_glob_39 from "../content/packages/bus/api/react/index.md?collection=docs"
import * as __fd_glob_38 from "../content/packages/constants/api/coordinates/index.md?collection=docs"
import * as __fd_glob_37 from "../content/packages/constants/api/units/index.md?collection=docs"
import * as __fd_glob_36 from "../content/packages/constants/api/color/index.md?collection=docs"
import * as __fd_glob_35 from "../content/toolkits/design-toolkit/guides/react.mdx?collection=docs"
import * as __fd_glob_34 from "../content/toolkits/design-foundation/guides/tailwind.mdx?collection=docs"
import * as __fd_glob_33 from "../content/packages/math/api/index.md?collection=docs"
import * as __fd_glob_32 from "../content/packages/logger/api/index.md?collection=docs"
import * as __fd_glob_31 from "../content/packages/bus/api/index.md?collection=docs"
import * as __fd_glob_30 from "../content/toolkits/map-toolkit/index.mdx?collection=docs"
import * as __fd_glob_29 from "../content/toolkits/design-toolkit/index.mdx?collection=docs"
import * as __fd_glob_28 from "../content/tooling/vitest-config/index.mdx?collection=docs"
import * as __fd_glob_27 from "../content/toolkits/design-foundation/index.mdx?collection=docs"
import * as __fd_glob_26 from "../content/tooling/typescript-config/index.mdx?collection=docs"
import * as __fd_glob_25 from "../content/tooling/smeegl/index.mdx?collection=docs"
import * as __fd_glob_24 from "../content/tooling/prettier-config/index.mdx?collection=docs"
import * as __fd_glob_23 from "../content/tooling/eslint-config/index.mdx?collection=docs"
import * as __fd_glob_22 from "../content/tooling/postcss-tailwind-css-modules/index.mdx?collection=docs"
import * as __fd_glob_21 from "../content/tooling/biome-config/index.mdx?collection=docs"
import * as __fd_glob_20 from "../content/packages/web-worker/index.mdx?collection=docs"
import * as __fd_glob_19 from "../content/packages/websocket/index.mdx?collection=docs"
import * as __fd_glob_18 from "../content/packages/temporal/index.mdx?collection=docs"
import * as __fd_glob_17 from "../content/packages/predicates/index.mdx?collection=docs"
import * as __fd_glob_16 from "../content/packages/math/index.mdx?collection=docs"
import * as __fd_glob_15 from "../content/packages/ntds/index.mdx?collection=docs"
import * as __fd_glob_14 from "../content/packages/logger/index.mdx?collection=docs"
import * as __fd_glob_13 from "../content/packages/icons/index.mdx?collection=docs"
import * as __fd_glob_12 from "../content/packages/formatters/index.mdx?collection=docs"
import * as __fd_glob_11 from "../content/packages/geo/index.mdx?collection=docs"
import * as __fd_glob_10 from "../content/packages/hotkey-manager/index.mdx?collection=docs"
import * as __fd_glob_9 from "../content/packages/dataset/index.mdx?collection=docs"
import * as __fd_glob_8 from "../content/packages/bus/index.mdx?collection=docs"
import * as __fd_glob_7 from "../content/packages/core/index.mdx?collection=docs"
import * as __fd_glob_6 from "../content/packages/constants/index.mdx?collection=docs"
import * as __fd_glob_5 from "../content/getting-started/index.mdx?collection=docs"
import { default as __fd_glob_4 } from "../content/packages/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../content/toolkits/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../content/tooling/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/getting-started/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content", {"meta.json": __fd_glob_0, "getting-started/meta.json": __fd_glob_1, "tooling/meta.json": __fd_glob_2, "toolkits/meta.json": __fd_glob_3, "packages/meta.json": __fd_glob_4, }, {"getting-started/index.mdx": __fd_glob_5, "packages/constants/index.mdx": __fd_glob_6, "packages/core/index.mdx": __fd_glob_7, "packages/bus/index.mdx": __fd_glob_8, "packages/dataset/index.mdx": __fd_glob_9, "packages/hotkey-manager/index.mdx": __fd_glob_10, "packages/geo/index.mdx": __fd_glob_11, "packages/formatters/index.mdx": __fd_glob_12, "packages/icons/index.mdx": __fd_glob_13, "packages/logger/index.mdx": __fd_glob_14, "packages/ntds/index.mdx": __fd_glob_15, "packages/math/index.mdx": __fd_glob_16, "packages/predicates/index.mdx": __fd_glob_17, "packages/temporal/index.mdx": __fd_glob_18, "packages/websocket/index.mdx": __fd_glob_19, "packages/web-worker/index.mdx": __fd_glob_20, "tooling/biome-config/index.mdx": __fd_glob_21, "tooling/postcss-tailwind-css-modules/index.mdx": __fd_glob_22, "tooling/eslint-config/index.mdx": __fd_glob_23, "tooling/prettier-config/index.mdx": __fd_glob_24, "tooling/smeegl/index.mdx": __fd_glob_25, "tooling/typescript-config/index.mdx": __fd_glob_26, "toolkits/design-foundation/index.mdx": __fd_glob_27, "tooling/vitest-config/index.mdx": __fd_glob_28, "toolkits/design-toolkit/index.mdx": __fd_glob_29, "toolkits/map-toolkit/index.mdx": __fd_glob_30, "packages/bus/api/index.md": __fd_glob_31, "packages/logger/api/index.md": __fd_glob_32, "packages/math/api/index.md": __fd_glob_33, "toolkits/design-foundation/guides/tailwind.mdx": __fd_glob_34, "toolkits/design-toolkit/guides/react.mdx": __fd_glob_35, "packages/constants/api/color/index.md": __fd_glob_36, "packages/constants/api/units/index.md": __fd_glob_37, "packages/constants/api/coordinates/index.md": __fd_glob_38, "packages/bus/api/react/index.md": __fd_glob_39, "packages/bus/api/broadcast/index.md": __fd_glob_40, "toolkits/design-toolkit/api/components/badge/index.md": __fd_glob_41, "toolkits/design-toolkit/api/components/button/index.md": __fd_glob_42, "toolkits/design-toolkit/api/components/dialog/index.md": __fd_glob_43, "toolkits/design-toolkit/api/components/table/index.md": __fd_glob_44, "toolkits/design-toolkit/api/components/text-field/index.md": __fd_glob_45, });