/*
 * Copyright 2025 Hypergiant Galactic Systems Inc. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

/**
 * THIS IS A GENERATED FILE. DO NOT ALTER DIRECTLY.
 * Generated by smeegl.
 */

export const AIR_ASSUMED_FRIEND = '74341af6';
export const AIR_BASE_FRIEND = '20ddeb17';
export const AIR_BASE_HOSTILE = 'e15c7861';
export const AIR_BASE_UNKNOWN = 'ec8ea16a';
export const AIR_FRIEND = '3a55c60b';
export const AIR_GROUP_FRIEND = '88494c29';
export const AIR_GROUP_HOSTILE = '2095f16d';
export const AIR_GROUP_UNKNOWN = '2d472866';
export const AIR_HOSTILE = 'f547ac03';
export const AIR_NEUTRAL = 'ad9d3698';
export const AIR_PENDING = 'e06c7f22';
export const AIR_SUSPECT = 'a72096c4';
export const AIR_UNKNOWN = 'f8957508';
export const BASE_FRIEND = '205d8cd6';
export const BASE_HOSTILE = '0d3f0a20';
export const BASE_UNKNOWN = '00edd32b';
export const CARRIER_FRIEND = '2a04a374';
export const CARRIER_HOSTILE = '35ed91cb';
export const CARRIER_UNKNOWN = '383f48c0';
export const COMMUNICATIONS = 'a64b4142';
export const HELICOPTER_FRIEND = '9511b69d';
export const HELICOPTER_HOSTILE = 'ec84de02';
export const HELICOPTER_UNKNOWN = 'e1560709';
export const LAND_ASSUMED_FRIEND = 'a475c8e7';
export const LAND_FRIEND = 'a5a01e68';
export const LAND_HOSTILE = '21636939';
export const LAND_NEUTRAL = '79b9f3a2';
export const LAND_PENDING = '3448ba18';
export const LAND_SUSPECT = '730453fe';
export const LAND_UNKNOWN = '2cb1b032';
export const MINE_FIELD = 'af8741d0';
export const MISSILE_FRIEND = '3dbfba81';
export const MISSILE_HOSTILE = 'f82d2c41';
export const MISSILE_UNKNOWN = 'f5fff54a';
export const POL = '688d0c19';
export const PORT = '42ddbcbf';
export const RUNWAY = 'cc2f9dab';
export const SAM = '5e0f5e44';
export const STRUCTURE = 'c15de452';
export const SUB_GROUP_FRIEND = '7f69e6f5';
export const SUB_GROUP_HOSTILE = 'af074f38';
export const SUB_GROUP_UNKNOWN = 'a2d59633';
export const SUB_SURFACE_ASSUMED_FRIEND = '60936458';
export const SUB_SURFACE_FRIEND = '093bcb98';
export const SUB_SURFACE_HOSTILE = '9c7200f0';
export const SUB_SURFACE_NEUTRAL = 'c4a89a6b';
export const SUB_SURFACE_PENDING = '8959d3d1';
export const SUB_SURFACE_SUSPECT = 'ce153a37';
export const SUB_SURFACE_UNKNOWN = '91a0d9fb';
export const SURFACE_ASSUMED_FRIEND = '39d2891a';
export const SURFACE_FRIEND = '45dc7e6a';
export const SURFACE_GROUP_FRIEND = 'a4aa05df';
export const SURFACE_GROUP_HOSTILE = '7467450d';
export const SURFACE_GROUP_UNKNOWN = '79b59c06';
export const SURFACE_HOSTILE = 'cf8d7475';
export const SURFACE_NEUTRAL = '9757eeee';
export const SURFACE_PENDING = 'daa6a754';
export const SURFACE_SUSPECT = '9dea4eb2';
export const SURFACE_UNKNOWN = 'c25fad7e';
export const TARGET = '1fd6c09c';
export const TORPEDO_FRIEND = '69ff18b5';
export const TORPEDO_HOSTILE = 'd9cd9856';
export const TORPEDO_UNKNOWN = 'd41f415d';
