name: 🐛 Bug Report
description: File a bug report
body:
  - type: markdown
    attributes:
      value: "#### Thanks for filing an issue! Before you submit, search open/closed [issues](https://github.com/gohypergiant/standard-toolkit/issues) before submitting."

  - type: markdown
    attributes:
      value: "# 🐛 Bug Report"

  - type: markdown
    attributes:
      value: Bug reports that don't follow this template will be closed.

  - type: textarea
    id: general-summary
    attributes:
      label: Provide a general summary of the issue here
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 🤔 Expected Behavior?
      description: Tell us what should happen
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: 😢 Current Behavior
      description: |
        Tell us what happens instead of the expected behavior.
        If you are seeing an error, please include the full error message and stack trace.
    validations:
      required: true

  - type: textarea
    id: possible-solution
    attributes:
      label: 🤩 Possible Solution
      description: Suggest a fix/reason for the bug
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Participation
      options:
        - label: I am willing to submit a pull request for this change.
          required: false

  - type: markdown
    attributes:
      value: "<small>Please **do not** open a pull request until this issue has been accepted by the team.</small>"

  - type: textarea
    id: context
    attributes:
      label: 📜 Context
      description: |
        Providing context helps us come up with a solution that is most useful in the real world.
        How has this issue affected you? What are you trying to accomplish?
    validations:
      required: false

  - type: textarea
    id: base-reproduction
    attributes:
      label: 🖥️ Steps to Reproduce
      description: |
        Provide a minimal test case that can reproduce the problem. Include a CodeSandBox, link to sample repos, or specific doc examples to help us test your issue more easily.
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## 🌍 Your Environment"

  - type: dropdown
    id: affected-packages
    attributes:
      label: Which package(s) are the source of the bug?
      options:
        - constants
        - converters
        - core
        - design-system
        - formatters
        - geo
        - math
        - predicates
        - temporal
        - web-worker
        - websocket
        - Don't known / other
      multiple: true
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the package are you running?
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other
    validations:
      required: true

  - type: input
    id: other
    attributes:
      label: If other, please specify.

  - type: input
    id: operating-system
    attributes:
      label: What operating system are you using?
    validations:
      required: true
