---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: accelint_design-toolkit
  title: Design Toolkit
  description: >-
    An open-source component library to serve as part of the entire ecosystem of
    UX for Accelint.


    Dependencies:

    accelint_biome-config@1.0.1, accelint_bus@1.4.0,
    accelint_constellation-tracker@1.0.0, accelint_core@0.4.2,
    accelint_icons@2.0.4, accelint_temporal@0.1.1,
    accelint_typescript-config@0.1.3, accelint_vitest-config@0.1.4
  annotations:
    backstage.io/edit-url: https://github.com/gohypergiant/standard-toolkit/blob/main/design-toolkit/components/catalog-info.yaml
    backstage.io/techdocs-ref: dir:.
    package/version: 6.0.0
    github.com/project-slug: gohypergiant/standard-toolkit
  links:
    - url: https://github.com/gohypergiant/standard-toolkit/tree/main/design-toolkit/components
      title: Documentation
      icon: docs
      type: documentation
  tags:
    - design-tk
    - ui
    - tooling
spec:
  type: library
  lifecycle: production
  owner: group:default/pathfinder
  dependsOn:
    - component:accelint_biome-config
    - component:accelint_bus
    - component:accelint_constellation-tracker
    - component:accelint_core
    - component:accelint_icons
    - component:accelint_temporal
    - component:accelint_typescript-config
    - component:accelint_vitest-config
