name: Release
on:
  push:
    branches:
      - main
env:
  TURBO_TELEMETRY_DISABLED: 1
  RUNNER_NODE_VERSION: 22
  RUNNER_PNPM_VERSION: 10.9.0 # specified in root package.json
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to create release (changesets/action)
      pull-requests: write # to post issue comments (changesets/action)
      issues: write # to create pull request (changesets/action)
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.RUNNER_PNPM_VERSION }}
          run_install: false
      - uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"
          node-version: ${{ env.RUNNER_NODE_VERSION }}
          cache: "pnpm"
      - run: pnpm install
      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: changesets/action@v1
        with:
          publish: pnpm run changeset:release
          version: pnpm run changeset:version
          commit: "build: version packages"
          title: "Changeset Action: Version Packages + Publish"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
