name: Release
on:
  push:
    branches:
      - main
env:
  TURBO_TELEMETRY_DISABLED: 1
  RUNNER_NODE_VERSION: 18
  RUNNER_PNPM_VERSION: 9.11.0 # specified in root package.json
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.RUNNER_PNPM_VERSION }}
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.RUNNER_NODE_VERSION }}
          cache: "pnpm"
      - run: pnpm install
      - uses: changesets/action@v1
        with:
          publish: false
          commit: "build: version packages"
          title: "Changeset Action: Version Packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
