name: Storybook Story Audit

on:
  push:
    branches: ["main"]
  pull_request:
    paths:
      - 'design-toolkit/components/src/**/*.stories.ts'
      - 'design-toolkit/components/src/**/*.stories.tsx'
      - '.storybook/**'
    types: [opened, synchronize]
env:
  TURBO_TELEMETRY_DISABLED: 1
  RUNNER_NODE_VERSION: 22
  RUNNER_PNPM_VERSION: 10.9.0 # specified in root package.json
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  validate-stories:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Use Turbo cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.RUNNER_PNPM_VERSION }}
          run_install: false

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.RUNNER_NODE_VERSION }}
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Validate story structure
        run: |
          cd design-toolkit/components
          pnpm audit:stories:ci

      # - name: Comment PR on failure
      #   if: failure()
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       github.rest.issues.createComment({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: `## 📚 Story Structure Validation Failed

      #         The Storybook story structure validation found issues that need to be addressed.

      #         **To fix:**
      #         1. Run \`pnpm --filter @accelint/design-toolkit audit:stories\` locally to see detailed issues
      #         2. Review the [Story Guidelines](design-toolkit/components/.storybook/docs/STORY_GUIDELINES.md)
      #         3. Use shared utilities from \`^storybook/utils\`
      #         4. Ensure all stories follow the standardized patterns
      #       });
